# -*- coding: utf-8 -*-
"""matterport-demo-nucleus-train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zfv5P9sy_X-qmX0Pc2W7k4Sa7CZhBQkN
"""

# mount drive
from google.colab import drive
drive.mount('/content/drive')

# !pip install keras==2.2.5

# !pip install keras==2.3.0 
# !pip install tensorflow==1.15.0rc2

# !pip install keras==2.1.0

# Commented out IPython magic to ensure Python compatibility.
# tf 1.15.2
# %tensorflow_version 1.x

import tensorflow
print(tensorflow.__version__)

# try fix AttributeError: 'str' object has no attribute 'decode'
# !pip install h5py==2.10.0

import os
root = "/content/drive/MyDrive/data/summer-project/Mask_RCNN/samples/nucleus/"
os.chdir(root)
!pwd

# import nucleus

# create data folder with only 4 image subfolders to check mask r-cnn can finish training
# %mkdir ../../simple-dataset
# 1st set of 4 stage1_train
# %cp -r ../../datasets/nucleus/stage1_train/0a7d30b252359a10fd298b638b90cb9ada3acced4e0c0e5a3692013f432ee4e9 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0acd2c223d300ea55d0546797713851e818e5c697d073b7f4091b96ce0f3d2fe ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/00ae65c1c6631ae6f2be1a449902976e6eb8483bf6b0740d00530220832c6d3e ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0b0d577159f0d6c266f360f7b8dfde46e16fa665138bf577ec3c6f9c70c0cd1e ../../simple-dataset

# 1st 4 validation
# %cp -r ../../datasets/nucleus/stage1_train/0c2550a23b8a0f29a7575de8c61690d3c31bc897dd5ba66caec201d201a278c2 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/92f31f591929a30e4309ab75185c96ff4314ce0a7ead2ed2c2171897ad1da0c7 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1e488c42eb1a54a3e8412b1f12cde530f950f238d71078f2ede6a85a02168e1f ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/c901794d1a421d52e5734500c0a2a8ca84651fb93b19cec2f411855e70cae339 ../../simple-dataset

# 2nd set of 4
# %cp -r ../../datasets/nucleus/stage1_train/0b2e702f90aee4fff2bc6e4326308d50cf04701082e718d4f831c8959fbcda93 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0bda515e370294ed94efd36bd53782288acacb040c171df2ed97fd691fc9d8fe ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0bf4b144167694b6846d584cf52c458f34f28fcae75328a2a096c8214e01c0d0 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0bf33d3db4282d918ec3da7112d0bf0427d4eafe74b3ee0bb419770eefe8d7d6 ../../simple-dataset


# 3rd set of 4, 1 is repeat validation don't copy
# ### %cp -r ../../datasets/nucleus/stage1_train/0c2550a23b8a0f29a7575de8c61690d3c31bc897dd5ba66caec201d201a278c2 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0c6507d493bf79b2ba248c5cca3d14df8b67328b89efa5f4a32f97a06a88c92c ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0d2bf916cc8de90d02f4cd4c23ea79b227dbc45d845b4124ffea380c92d34c8c ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0d3640c1f1b80f24e94cc9a5f3e1d9e8db7bf6af7d4aba920265f46cadc25e37 ../../simple-dataset

# # 4th set of 4
# %cp -r ../../datasets/nucleus/stage1_train/0ddd8deaf1696db68b00c600601c6a74a0502caaf274222c8367bdc31458ae7e ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0e4c2e2780de7ec4312f0efcd86b07c3738d21df30bb4643659962b4da5505a3 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0e5edb072788c7b1da8829b02a49ba25668b09f7201cf2b70b111fc3b853d14f ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/0e21d7b3eea8cdbbed60d51d72f4f8c1974c5d76a8a3893a7d5835c85284132e ../../simple-dataset

# # 5th set of 4
# 0ea22 uncommmented in nucelus.py as valid
# %cp -r ../../datasets/nucleus/stage1_train/0ea221716cf13710214dcd331a61cea48308c3940df1d28cfc7fd817c83714e1 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1a75de9e11303142864efed27e69ea1960dbd82ca910de221a777ed2caf35a6b ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1a75e9f15481d11084fe66bc2a5afac6dc5bec20ed56a7351a6d65ef0fe8762b ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1a11552569160f0b1ea10bedbd628ce6c14f29edec5092034c2309c556df833e ../../simple-dataset


# # # 6th set of 4
# %cp -r ../../datasets/nucleus/stage1_train/1b2bf5933b0fb82918d278983bee66e9532b53807c3638efd9af66d20a2bae88 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1b44d22643830cd4f23c9deadb0bd499fb392fb2cd9526d81547d93077d983df ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1b518cd2ea84a389c267662840f3d902d0129fab27696215db2488de6d4316c5 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1b6044e4858a9b7cee9b0028d8e54fbc8fb72e6c4424ab5b9f3859bfc72b33c5 ../../simple-dataset

# # 7th set of 4
# %cp -r ../../datasets/nucleus/stage1_train/1bd0f2b3000b7c7723f25335fabfcdddcdf4595dd7de1b142d52bb7a186885f0 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1c2f9e121fc207efff79d46390df1a740566b683ff56a96d8cabe830a398dd2e ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1c8b905c9519061d6d091e702b45274f4485c80dcf7fb1491e6b2723f5002180 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1c681dfa5cf7e413305d2e90ee47553a46e29cce4f6ed034c8297e511714f867 ../../simple-dataset

# # 8th set of 4
# %cp -r ../../datasets/nucleus/stage1_train/1d02c4b5921e916b9ddfb2f741fd6cf8d0e571ad51eb20e021c826b5fb87350e ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1d4a5e729bb96b08370789cad0791f6e52ce0ffe1fcc97a04046420b43c851dd ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1d5f4717e179a03675a5aac3fc1c862fb442ddc3e373923016fd6b1430da889b ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/01d44a26f6680c42ba94c9bc6339228579a95d0e2695b149b7cc0c9592b21baf ../../simple-dataset

# # 9th set of 4
# %cp -r ../../datasets/nucleus/stage1_train/1db1cddf28e305c9478519cfac144eee2242183fe59061f1f15487e925e8f5b5 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1e61ecf354cb93a62a9561db87a53985fb54e001444f98112ed0fc623fad793e ../../simple-dataset
# ###%cp -r ../../datasets/nucleus/stage1_train/1e488c42eb1a54a3e8412b1f12cde530f950f238d71078f2ede6a85a02168e1f ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1e8408fbb1619e7a0bcdd0bcd21fae57e7cb1f297d4c79787a9d0f5695d77073 ../../simple-dataset

# # 10th set of 4
# %cp -r ../../datasets/nucleus/stage1_train/1ec74a26e772966df764e063f1391109a60d803cff9d15680093641ed691bf72 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1ee4a111f0e0bb9b001121b94ff98ca736fad03797b25285fe33a47046b3e4b0 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1f6b7cead15344593b32d5f2345fc26713dc74d9b31306c824209d67da401fd8 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/1f9e429c12f4477221b5b855a5f494fda2ef6d064ff75b061ffaf093e91758c5 ../../simple-dataset

# # 11th set of 4
# %cp -r ../../datasets/nucleus/stage1_train/1f0008060150b5b93084ae2e4dabd160ab80a95ce8071a321b80ec4e33b58aca ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/2a1a294e21d76efd0399e4eb321b45f44f7510911acd92c988480195c5b4c812 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/2a2032c4ed78f3fc64de7e5efd0bec26a81680b07404eaa54a1744b7ab3f8365 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/2ab91a4408860ae8339689ed9f87aa9359de1bdd4ca5c2eab7fff7724dbd6707 ../../simple-dataset

# # 12th set of 4
# %cp -r ../../datasets/nucleus/stage1_train/2abc40c118bc7303592c8bb95a80361e27560854b8971ab34dcf91966575b1f2 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/2ad489c11ed8b77a9d8a2339ac64ffc38e79281c03a2507db4688fd3186c0fe5 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/2b50b1e3fa5c5aa39bc84ebfaea9961b7199c4d2488ae0b48d0b3459807d59d2 ../../simple-dataset
# %cp -r ../../datasets/nucleus/stage1_train/2bf594e9d06f78b4b79d7ffb395497a0a91126b6b0d710d7a9cee21f5c3bd177 ../../simple-dataset

# !python nucleus.py train --dataset=../../datasets/nucleus/ --subset=train --weights=imagenet
# train on simple dataset, which is is same as datasets/nucleus but has less stage1_train subfolders
!python nucleus.py train --dataset=../../simple-dataset/nucleus --subset=train --weights=imagenet